const projects = [
  { n: '01', title: 'Hermes', category: 'AI SYSTEMS / PERSONAL PROJECT', description: 'A multi-agent AI system running in a Linux environment. An exploration of agent workflows, automation, and the infrastructure that keeps them running.', tags: ['AI agents', 'Linux', 'SSH', 'Automation'], detail: 'Hands-on work configuring environments, managing processes, and troubleshooting connectivity across a multi-agent setup.' },
  { n: '02', title: 'Business websites', category: 'WEB DEVELOPMENT / FREELANCE', description: 'Web development for businesses in Dubai and Bahrain, translating client requirements into websites and ongoing improvements.', tags: ['React', 'Next.js', 'WordPress', 'TypeScript'], detail: 'Working directly with clients to understand requirements, implement changes, and troubleshoot website issues.' },
  { n: '03', title: 'Paper trading platform', category: 'WEB APPLICATION / PERSONAL PROJECT', description: 'A Next.js project exploring paper trading, developed alongside a separate trading-agent dashboard.', tags: ['Next.js', 'React', 'Local development'], detail: 'An ongoing project exploring trading interfaces and running multiple development environments side by side.' },
];
export default function Home() {
 return <main id="top">
  <a className="skip" href="#work">Skip to work</a>
  <header><a className="brand" href="#top" aria-label="Hibban Ullah home">hu<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#skills">Toolkit <span>↗</span></a></nav></header>
  <section className="hero"><div className="eyebrow"><span className="dot"/> HIBBAN ULLAH <span className="slash">/</span> COMPUTER SCIENCE & DEVELOPMENT</div><h1>Curiosity.<br/>Code.<br/><span>Things that work.</span></h1><div className="hero-bottom"><p>I’m Hibban, a computer science student at San Francisco State University. I build websites, explore AI systems, and learn by making things.</p><a className="work-link" href="#work">Explore my work <span>↓</span></a></div><div className="hero-meta"><span>WEB DEVELOPMENT · AI & AUTOMATION · LINUX</span><span>PORTFOLIO / 2026</span></div></section>
  <section id="work" className="work"><div className="section-heading"><h2>Selected work<span> (03)</span></h2><p>Client work & personal explorations</p></div>{projects.map(p=><article className="project" key={p.n}><div className="project-number">{p.n}</div><div className="project-main"><p className="eyebrow">{p.category}</p><h3>{p.title}</h3><p className="description">{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><details><summary>Behind the project <span>+</span></summary><p>{p.detail}</p></details></div><span className="project-mark" aria-hidden="true">{p.n==='01'?'⌘':p.n==='02'?'↗':'[ ]'}</span></article>)}</section>
  <section className="about" id="about"><div><p className="eyebrow">A LITTLE ABOUT ME</p><h2>Learning by<br/><span>building.</span></h2></div><div className="about-copy"><p>I’m studying computer science at San Francisco State University, with an interest in web development, AI automation, and the systems underneath.</p><p>My experience spans freelance websites for businesses in Dubai and Bahrain, a personal Hermes multi-agent system, and experiments with Linux and virtual machines. I enjoy breaking down unfamiliar problems and figuring out how the pieces fit together.</p><div className="education"><span>EDUCATION</span><strong>San Francisco State University</strong><p>Computer Science</p></div></div></section>
  <section id="skills" className="skills"><div className="section-heading"><h2>My toolkit</h2><p>Tools I work and learn with</p></div><div className="skill-grid">{[['Development','JavaScript & TypeScript','React & Next.js','HTML & CSS','Java & Python'],['Systems','Linux / Ubuntu','Bash & Zsh','SSH & Terminal','VirtualBox & Vagrant'],['Workflow','Git & GitHub','VS Code & IntelliJ IDEA','Hermes & AI agents','Networking & troubleshooting']].map(([name,...items])=><div key={name}><h3>{name}</h3>{items.map(i=><p key={i}>{i}</p>)}</div>)}</div></section>
  <footer><a className="brand" href="#top">hu<span>.</span></a><p>Hibban Ullah <span>© 2026</span></p><a href="#top">Back to top ↑</a></footer>
 </main>
}
